### ISSUE TITLE
Reference implementation for Rapid Server

### ISSUE THREAD

**Issue by ralfhandl** [oasis-open/odata-rapid#54]
Easy-to-use modular server for Node.js based on expressjs
- [ ] "surface" with
  - [ ] URL parser
  - [ ] Payload de-serializer with (optional?) schema validation
  - [ ] Payload serializer with optional schema validation
- [ ] Adapter for logic: lego brick that can be put between "surface" and database adapter(s)
- [ ] Adapter for popular free SQL database(s)
- [ ] Adapter for popular free NoSQL database(s)

**Comment by mikepizzo** [comment]
JStack owns a node.js service -- perhaps we can work with them to enhance that service:

 https://jaydata.org/jaystack-odata-v4-server

**Comment by mikepizzo** [comment]
a couple other node.js odata services:
https://www.npmjs.com/package/simple-odata-server
https://www.npmjs.com/package/node-odata
